import { ReadApiService } from "./read-api";
import { MintingApiService } from "./minting-api";
import { CNFTApiService } from "./cnft-api";
import { GiftApiService } from "./gift-api";
import { StorageApiService } from "./storage-api";

class GetgemsService {
    public readApi: ReadApiService;
    public mintingApi: MintingApiService;
    public cNftApi: CNFTApiService;
    public giftApi: GiftApiService;
    public storageApi: StorageApiService;

    constructor(apiKey: string) {
        this.readApi = new ReadApiService(apiKey);
        this.mintingApi = new MintingApiService(apiKey);
        this.cNftApi = new CNFTApiService(apiKey);
        this.giftApi = new GiftApiService(apiKey);
        this.storageApi = new StorageApiService(apiKey);
    }
}

export { GetgemsService as Getgems };

export {
    DefaultErrorObject,
    UpdateResponse,
    UpdateData,
    UpdateRequest,
    CollectionUpdateRequest,
    NftButton,
    SyncRequest,
    MintingRequest,
    BatchMintingItem,
    BatchMintingRequest,
    V2BatchMintingRequest,
    NftAttribute,
    FailedResponse,
    BatchMintingStatusResponse,
    MintingStatusObject,
    MintingStatusResponse,
    UploadResponse,
    OwnershipChangeEvent,
    NftItem,
    NftItemFull,
    FixPriceSale,
    Auction,
    NftCollectionFull,
    NftItemAttribute,
    NftItemsResponse,
    NftItemsFullResponse,
    NftItemResponse,
    NftItemFullResponse,
    NftCollectionFullResponse,
    MintingMessageResponse,
    MintingWalletBalanceResponse,
    CNFTRequest,
    CNFTRequestItem,
    OpenCNFTResult,
    CNFTItem,
    AddCNFTToCollectionResponse,
    NftCollectionStatsResponse,
    NftCollectionStats,
    NftItemHistoryResponse,
    NftItemHistory,
    NftItemHistoryItem,
    NftItemsUpdateResponse,
    HistoryTypeMint,
    HistoryTypeTransfer,
    HistoryTypeCancelSale,
    HistoryTypeSold,
    HistoryTypePutUpForSale,
    HistoryTypePutUpForAuction,
    HistoryTypeCancelAuction,
    HistoryTypeBurn,
    BuyNftFixPriceRequest,
    PutUpNftForSaleRequest,
    TransactionResponse,
    Transaction,
    TransactionListItem,
    NftCollectionStatsCountResponse,
    NftCollectionStatsCount,
    NftCollectionOwnersTopResponse,
    NftCollectionOwnersTop,
    NftCollectionOwnersTopItem,
    NftCollectionAttributesResponse,
    NftCollectionAttributes,
    NftCollectionAttribute,
    NftItemsByAddressRequestBody,
    NftItemsFullNoCursorResponse,
    NftCollectionMetadata,
    CreateNewCollectionRequest,
    NftCollectionCreatingStatusResponse,
    NftCollectionCreatingStatus,
    TransferResponse,
    TransferOffchainGiftRequest,
    NftCollectionFloorResponse,
    ReindexResponse,
    UserTradingInfoResponse,
    NftCollectionsFullResponse,
    NftStickerCollectionsFullResponse,
    StickerMarketplace,
    GiftTransferRequest,
    ConfirmTransferRequest,
    RequestTransferResponse,
    ConfirmTransferResponse,
    StorageBoxIdResponse,
    StorageUploadCredentials,
    StorageUploadCredentialsResponse,
    SetStorageCollectionRequest,
    SetStorageCollectionResponse,
    CheckTxPayload,
    TonTxStatusResponse,
    TonTxStatus,
    MintingListItem,
    MintingListResponse,
    CollectionsTopResponse,
    CollectionsTopItem,
    OfferListResponse,
    Offer,
    CreateNftOfferPayload,
    CreateCollectionOfferPayload,
    AcceptOfferRequest,
    CancelOfferRequest,
    UserOfferListResponse,
    OfferWithStatus,
    EUpdateDataStatus,
    EMintingStatus,
    EOwnershipChangeEventType,
    ENftItemKind,
    ENftItemWarning,
    ESaleType,
    EContractType,
    ENftItemsUpdateResponseType,
    EHistoryType,
    ECurrency,
    EReindexResponseStatus,
    ELang,
    ESignatureDataType,
    ETonTxState,
    EMintingListItemType,
    EMintingListItemStatus
} from './schemas';